######################################################################
##
## Filename: generate_code.udo
## Created on: Wed Jun 27 18:50:48 中国标准时间 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
